# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doct',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False)),
                ('Phone', models.CharField(max_length=20)),
                ('eMail', models.EmailField(max_length=30)),
                ('FName', models.CharField(max_length=20)),
                ('LName', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=50)),
                ('OID', models.IntegerField()),
                ('Description', models.CharField(max_length=100)),
                ('QText', models.CharField(max_length=100)),
            ],
        ),
    ]
